id: P85C25636
initial_creation_type: input
source_metadata:
  Title: Bāhyarthasiddhikārikānāma
  Editor: Shastri, N. A
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Bāhyarthasiddhikārikānāma:
    Text Version: Roman
    Input Personnel: DSBC Staff
    Input Date: '2013'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:53:22.394794'
last_modified_at: '2022-03-08T16:53:22.394802'
